---

- name: "Notify Telegram"
  community.general.telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      parse_mode: "Markdown"
      text: "{{ notification_text }}"
  when: notify_telegram is defined
