- hosts: "{{hosts}}"
  vars:
    notification_text: "Maintenance done on {{ inventory_hostname }} at {{ ansible_date_time.date }} {{ ansible_date_time.time }}. OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
  roles:
    - role: "debian"
      when: ansible_os_family == "Debian"
      become: true
    - role: "redhat"
      when: ansible_os_family == "RedHat"
      become: true
  tasks:
    - name: "Notify Telegram"
      include_tasks: "../notify/roles/telegram/tasks/main.yml"
      when: notify_telegram is defined