--- 


- debug: 
    msg: "Task Debian"

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
- name: "Upgrade all packages"
  ansible.builtin.apt:
    upgrade: dist

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoremove: yes
