- ansible.builtin.include_tasks:
    file: join.yml
  when: enroll is defined and enroll == true
- ansible.builtin.include_tasks:
    file: leave.yml
  when: enroll is defined and enroll == false

- name: "Reboot after enroll/unenroll"
  reboot:
    reboot_timeout: 300
    msg: "Rebooting post enrollment/unenrollment"
  when: "ipaclient_reboot_after == true"